name: Publish Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
    - uses: actions/checkout@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Install dependencies
      run: |
        pip install . --group dev
    - name: Run tests
      run: |
        pytest

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    environment: release
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v7
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Install dependencies
      run: |
        pip install setuptools wheel build
    - name: Build
      run: |
        python -m build
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1

  # After the first non-prerelease 1.0 release, disable this job on 0.65.x,
  # even for later 0.65 releases, so they cannot overwrite the 1.0 stable docs.
  deploy_static_docs:
    runs-on: ubuntu-latest
    needs: [deploy]
    if: "!github.event.release.prerelease"
    steps:
    - uses: actions/checkout@v7
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Install dependencies
      run: |
        python -m pip install . --group dev
        python -m pip install sphinx-to-sqlite==0.1a1 "s3-credentials>=0.17"
    - name: Build docs.db
      run: |-
        cd docs
        DISABLE_SPHINX_INLINE_TABS=1 sphinx-build -b xml . _build
        sphinx-to-sqlite ../docs.db _build
        cd ..
    - name: Upload stable documentation database to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_DATASETTE_DOCS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_DATASETTE_DOCS_SECRET_KEY }}
      run: |-
        s3-credentials put-object datasette-docs docs.db docs.db \
          --content-type application/octet-stream

  deploy_docker:
    runs-on: ubuntu-latest
    needs: [deploy]
    if: "!github.event.release.prerelease"
    steps:
    - uses: actions/checkout@v7
    - name: Build and push to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |-
        sleep 60 # Give PyPI time to make the new release available
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        export REPO=datasetteproject/datasette
        docker build -f Dockerfile \
          -t $REPO:${GITHUB_REF#refs/tags/} \
          --build-arg VERSION=${GITHUB_REF#refs/tags/} .
        docker tag $REPO:${GITHUB_REF#refs/tags/} $REPO:latest
        docker push $REPO:${GITHUB_REF#refs/tags/}
        docker push $REPO:latest
